const c=window.SSC_CONFIG||{};const $=id=>document.getElementById(id);let db=null,user=null,last=null;
if(c.SUPABASE_URL&&c.SUPABASE_ANON_KEY&&window.supabase){db=supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY);$("status").textContent="Supabase configured. Login as your admin user."}else{$("status").textContent="Demo mode: add Supabase URL + publishable/anon key in config.js";$("login").disabled=true}
$("login").onclick=async()=>{const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return $("status").textContent="Enter admin email and password.";$("status").textContent="Logging in...";const{data,error}=await db.auth.signInWithPassword({email,password});if(error)return $("status").textContent=error.message;user=data.user;$("auth").hidden=true;$("manager").hidden=false;$("status").textContent="Logged in. You can now upload files and publish.";load();loadResults()};
$("upload").onclick=async()=>{if(!db||!user)return $("uploadMsg").textContent="Please login first.";const f=$("file").files[0],title=$("fileTitle").value.trim();if(!f)return $("uploadMsg").textContent="Choose a file first.";if(!title)return $("uploadMsg").textContent="Enter a display title.";$("uploadMsg").textContent="Uploading...";const name=f.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${user.id}/${Date.now()}-${name}`;const{error}=await db.storage.from("ssc-files").upload(path,f,{upsert:false});if(error)return $("uploadMsg").textContent=error.message;last={path,title,size:size(f.size)};$("noticeTitle").value=$("noticeTitle").value||title;$("noticeSize").value=$("noticeSize").value||last.size;$("noticePath").value=path;$("uploadMsg").textContent="Uploaded. The file path is ready to publish."};
$("publish").onclick=async()=>{if(!last)return $("status").textContent="Please upload a file first.";const title=$("noticeTitle").value.trim();if(!title)return $("status").textContent="Enter a notice title.";const{error}=await db.from("ssc_notices").insert({title,notice_date:$("noticeDate").value||null,file_path:last.path,file_size:$("noticeSize").value||last.size});if(error)return $("status").textContent=error.message;$("status").textContent="Notice published successfully.";resetNotice();load()};
$("publishResult").onclick=async()=>{if(!last)return $("resultMsg").textContent="Upload a file first using Upload File above.";const title=$("resultTitle").value.trim();const category=$("resultCategory").value;if(!title)return $("resultMsg").textContent="Enter a result title.";const{error}=await db.from("ssc_results").insert({category,title,result_date:$("resultDate").value||null,file_path:last.path,file_size:$("resultSize").value||last.size});if(error)return $("resultMsg").textContent=error.message;$("resultMsg").textContent="Result published successfully.";resetResult();loadResults()};
$("refresh").onclick=()=>{load();loadResults()};
function resetNotice(){$("file").value="";$('fileTitle').value="";$('noticeTitle').value="";$('noticeDate').value="";$('noticeSize').value="";$('noticePath').value="";$('uploadMsg').textContent="";last=null}
function resetResult(){$("resultTitle").value="";$('resultDate').value="";$('resultSize').value="";$('resultMsg').textContent="";last=null}
function size(b){let k=b/1024;return k<1024?k.toFixed(2)+" KB":(k/1024).toFixed(2)+" MB"}
async function load(){const{data,error}=await db.from("ssc_notices").select("*").order("created_at",{ascending:false});if(error)return $("noticeList").textContent=error.message;$("noticeList").innerHTML=(data||[]).map(n=>`<article><b>${esc(n.title)}</b><small>${esc(n.notice_date||"")} · ${esc(n.file_size||"")}</small>${n.file_path?`<a target="_blank" href="${esc(publicUrl(n.file_path))}">Open / Download File</a>`:""}</article>`).join("")||"<p>No notices yet.</p>"}
async function loadResults(){const{data,error}=await db.from("ssc_results").select("*").order("created_at",{ascending:false});if(error)return $("resultList").textContent="Run the updated supabase_setup.sql once, then refresh.";$("resultList").innerHTML=(data||[]).map(r=>`<article><b>${esc(r.category)} — ${esc(r.title)}</b><small>${esc(r.result_date||"")} · ${esc(r.file_size||"")}</small>${r.file_path?`<a target="_blank" href="${esc(publicUrl(r.file_path))}">Open Result File</a>`:""}</article>`).join("")||"<p>No results yet.</p>"}
function publicUrl(path){return db.storage.from("ssc-files").getPublicUrl(path).data.publicUrl}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
