(() => {
'use strict';
const c=window.SSC_CONFIG||{};const $=id=>document.getElementById(id);let db=null,user=null,lastFile=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const size=b=>b<1024*1024?(b/1024).toFixed(2)+' KB':(b/1024/1024).toFixed(2)+' MB';
async function isAdmin(){if(!user)return false;const r=await db.from('ssc_admins').select('user_id').eq('user_id',user.id).maybeSingle();return !r.error&&!!r.data}
function setStatus(t){$('status').textContent=t}
async function refresh(){
 const n=await db.from('ssc_notices').select('*').order('created_at',{ascending:false});
 $('noticeList').innerHTML=n.error?esc(n.error.message):(n.data||[]).map(x=>`<article><b>${esc(x.title)}</b><small>${esc(x.notice_date||'')} · ${esc(x.file_size||'')}</small>${x.file_path?`<a target="_blank" href="${esc(x.file_path.startsWith('http')?x.file_path:db.storage.from('ssc-files').getPublicUrl(x.file_path).data.publicUrl)}">Open PDF</a>`:''}</article>`).join('')||'<p>No notices yet.</p>';
 const r=await db.from('ssc_public_results').select('*').order('result_date',{ascending:false}).order('created_at',{ascending:false});
 $('resultList').innerHTML=r.error?esc(r.error.message):(r.data||[]).map(x=>`<article><b>${esc(x.category)} — ${esc(x.title)}</b><small>${esc(x.result_date||'')} · ${esc(x.file_size||'')}</small>${x.file_path?`<a target="_blank" href="${esc(x.file_path.startsWith('http')?x.file_path:db.storage.from('ssc-files').getPublicUrl(x.file_path).data.publicUrl)}">Open PDF</a>`:''}</article>`).join('')||'<p>No published results yet.</p>';
}
async function login(){const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return setStatus('Enter admin email and password.');setStatus('Logging in…');const r=await db.auth.signInWithPassword({email,password});if(r.error)return setStatus(r.error.message);user=r.data.user;if(!(await isAdmin())){await db.auth.signOut();user=null;return setStatus('Admin access required.')}$('auth').hidden=true;$('manager').hidden=false;setStatus('Logged in.');await refresh()}
async function upload(){const f=$('file').files[0];if(!f)return $('uploadMsg').textContent='Choose a file first.';const path=`${user.id}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;$('uploadMsg').textContent='Uploading…';const r=await db.storage.from('ssc-files').upload(path,f,{upsert:false,contentType:f.type||'application/octet-stream'});if(r.error)return $('uploadMsg').textContent=r.error.message;lastFile={path,url:db.storage.from('ssc-files').getPublicUrl(path).data.publicUrl,title:$('fileTitle').value.trim()||f.name,size:size(f.size)};$('noticePath').value=path;$('noticeTitle').value=$('noticeTitle').value||lastFile.title;$('noticeSize').value=$('noticeSize').value||lastFile.size;$('uploadMsg').textContent='File uploaded. Now publish it as a notice if required.'}
async function publishNotice(){if(!lastFile)return setStatus('Upload a file first.');const payload={title:$('noticeTitle').value.trim()||lastFile.title,notice_date:$('noticeDate').value||null,file_path:lastFile.path,file_size:$('noticeSize').value||lastFile.size};const r=await db.from('ssc_notices').insert(payload);if(r.error)return setStatus(r.error.message);setStatus('Notice published.');lastFile=null;$('file').value='';$('fileTitle').value='';$('noticeTitle').value='';$('noticeDate').value='';$('noticeSize').value='';$('noticePath').value='';await refresh()}
async function publishResult(){const f=$('file').files[0],title=$('resultTitle').value.trim();if(!title)return $('resultMsg').textContent='Enter a result title.';if(!f)return $('resultMsg').textContent='Choose the result PDF in Upload File first.';if(f.type!=='application/pdf')return $('resultMsg').textContent='Result must be a PDF.';$('resultMsg').textContent='Uploading result PDF…';const path=`${user.id}/results/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await db.storage.from('ssc-files').upload(path,f,{upsert:false,contentType:'application/pdf'});if(up.error)return $('resultMsg').textContent=up.error.message;const ins=await db.from('ssc_public_results').insert({category:$('resultCategory').value,title,result_date:$('resultDate').value||null,file_path:path,file_size:$('resultSize').value||size(f.size)});if(ins.error){await db.storage.from('ssc-files').remove([path]);return $('resultMsg').textContent=ins.error.message}$('resultMsg').textContent='Result published successfully.';$('file').value='';$('fileTitle').value='';$('resultTitle').value='';$('resultDate').value='';$('resultSize').value='';lastFile=null;await refresh()}
$('login').onclick=login;$('upload').onclick=upload;$('publish').onclick=publishNotice;$('publishResult').onclick=publishResult;$('refresh').onclick=refresh;$('logout').onclick=async()=>{await db?.auth.signOut();location.reload()};
if(c.SUPABASE_URL&&c.SUPABASE_ANON_KEY&&window.supabase){db=supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY);setStatus('Supabase configured. Login as an admin.')}else setStatus('Supabase configuration missing.');
})();
