const cfg=window.SSC_CONFIG||{};
const has=!!(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase);
let db=null;
if(has) db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);

const notices=[
 {date:'19',month:'AUG',year:'2026',title:'Important Notice regarding SSC Examinations',meta:'Notice',file:'#'},
 {date:'18',month:'AUG',year:'2026',title:'Examination calendar and candidate updates',meta:'Notice',file:'#'},
 {date:'14',month:'AUG',year:'2026',title:'Candidates are advised to regularly visit the Commission website',meta:'Notice',file:'#'},
 {date:'12',month:'AUG',year:'2026',title:'Recruitment examination related information',meta:'Notice',file:'#'},
 {date:'08',month:'AUG',year:'2026',title:'Admit Card and examination city information',meta:'Notice',file:'#'}
];
const exams=['Combined Graduate Level Examination','Combined Higher Secondary Level Examination','Junior Engineer Examination','Selection Post Examination','Constable (GD) Examination','Multi Tasking (Non-Technical) Staff Examination'];
const quick=[['📝','Apply Online','apply'],['🎫','Admit Card','admit'],['🔑','Answer Key','answer'],['🏆','Result','result']];
const faqs=[['How can I apply for an SSC examination?','Use the Apply Online option and complete registration, profile details and the examination application.'],['Where can I download my Admit Card?','Open the Admit Card section and select the relevant examination or regional link.'],['How can I check my result?','Use the Result section and select the relevant examination and result category.'],['Where can I find examination notices?','All important updates are listed in the Notice Board and can be opened from the notice card.']];

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function shell(){
 const app=document.getElementById('app');
 app.innerHTML=`
 <div class="topline"><div class="container"><span>Government of India</span><span><a href="#skip">Skip to main content</a> &nbsp;|&nbsp; हिन्दी</span></div></div>
 <header><div class="container brandrow"><a class="brand" href="#home" aria-label="SSC Home"><span class="ashoka">♜</span><div><strong style="display:block;font-size:18px;color:#651b1f">Staff Selection Commission</strong><small style="color:#706c6c">Government of India</small></div></a><div class="head-actions"><div class="searchbox"><input id="searchInput" aria-label="Search" placeholder="Search..."> 🔍</div><button class="login-btn" id="loginBtn">Login / Register</button></div></div></header>
 <nav class="nav"><div class="container nav-inner">
 ${nav('Home','home')}${nav('For Candidates','candidates', ['Apply Online','Admit Card','Answer Key','Result','Candidate Login'])}${nav('Examinations','exams',exams)}${nav('Notice Board','notices',['Latest Notices','Archive'])}${nav('About SSC','about',['About Commission','Functions','Contact Us'])}
 </div></nav>
 <main id="skip">
 <section class="hero"><div class="hero-inner"><div class="hero-copy"><span>STAFF SELECTION COMMISSION</span><h1>Recruitment and Examination Portal</h1><p>Access examinations, notices, results, admit cards and candidate services.</p><div><button class="primary" data-route="exams">Browse Examinations</button></div></div><div class="hero-art">SSC</div></div></section>
 <section class="notice-strip"><div class="ticker"><strong>Latest Updates</strong> &nbsp; Important examination notices and candidate information are published here. <a class="join" href="#notices">View Notices →</a></div></section>
 <section class="section" id="notices"><div class="container"><div class="section-head"><h2 class="section-title">Notice Board</h2><a href="#notices-all">View All →</a></div><div class="card notice-card"><div class="notice-list" id="noticeList"></div><div class="pager" id="pager"></div></div></div></section>
 <section class="section" id="quick"><div class="container"><div class="section-head"><h2 class="section-title">Quick Links</h2></div><div class="quick-grid">${quick.map(q=>`<a class="quick" href="#${q[2]}" data-route="${q[2]}"><span class="ico">${q[0]}</span><span><b>${q[1]}</b><small style="display:block;color:#777;margin-top:3px">Open service</small></span></a>`).join('')}</div></div></section>
 <section class="section"><div class="container"><div class="card calendar-card"><div class="calendar-head"><h2 class="section-title">SSC Calendar</h2><div class="month-nav"><button id="prevMonth">‹</button><b id="calMonth">August 2026</b><button id="nextMonth">›</button></div></div><div class="cal-list" id="calendarList"></div><a class="viewall" href="#calendar">View Full Calendar →</a></div></div></section>
 <section class="section exams"><div class="container exam-wrap"><div><h2 class="exam-title">Browse by Examinations</h2><p class="exam-sub">Explore examination notices, schedules and candidate resources.</p><button class="primary" data-route="exams">View All Examinations</button></div><div><div class="exam-track" id="examTrack"></div><div class="dots">● ○ ○</div></div></div></section>
 <section class="section"><div class="container"><div class="section-head"><h2 class="section-title">Important Information</h2></div><div class="promo-grid"><article class="promo"><div style="height:195px;background:linear-gradient(135deg,#f5e6e3,#dcb8b2);display:grid;place-items:center;font-size:42px;color:#651b1f">📢</div><div style="padding:16px"><b>Candidate Updates</b><p>Regularly check the Commission website for examination information.</p></div></article><article class="promo"><div style="height:195px;background:linear-gradient(135deg,#eee7d9,#d6c39c);display:grid;place-items:center;font-size:42px;color:#651b1f">📅</div><div style="padding:16px"><b>Examination Calendar</b><p>View upcoming examinations and important dates.</p></div></article><article class="promo"><div style="height:195px;background:linear-gradient(135deg,#e5ece9,#b7cdc6);display:grid;place-items:center;font-size:42px;color:#651b1f">🎓</div><div style="padding:16px"><b>Candidate Services</b><p>Access admit cards, results, answer keys and other services.</p></div></article></div></div></section>
 <section class="section"><div class="container faq-grid"><div class="faq-copy"><h2>Frequently Asked Questions</h2><p>Find quick answers to common questions about SSC examinations and candidate services.</p><button class="primary" data-route="faq">View All FAQs</button></div><div class="faq-list" id="faqList"></div></div></section>
 <section class="section initiatives"><div class="container"><div class="section-head"><h2 class="section-title">Other Initiatives</h2></div><div class="initiative-grid"><div class="initiative"><b>Digital India</b></div><div class="initiative"><b>Government of India</b></div><div class="initiative"><b>e-Governance</b></div><div class="initiative"><b>Citizen Services</b></div></div></div></section>
 </main>
 <footer class="footer"><div class="container footer-grid"><div><div class="footer-brand"><span style="font-size:32px">♜</span><b>Staff Selection Commission</b></div><p>Government of India. This portal provides information and online services related to SSC examinations.</p></div><div><h3>Useful Links</h3><a href="#home">Home</a><a href="#notices">Notice Board</a><a href="#exams">Examinations</a><a href="#result">Results</a></div><div><h3>Candidate Services</h3><a href="#admit">Admit Card</a><a href="#answer">Answer Key</a><a href="#apply">Apply Online</a><a href="#contact">Contact Us</a></div></div><div class="container footer-bottom"><span>© 2026 Staff Selection Commission</span><span>Privacy Policy &nbsp; | &nbsp; Terms &nbsp; | &nbsp; Sitemap</span></div></footer>`;
 bind(); renderNotices(1); renderCalendar(); renderExams(); renderFaq();
}
function nav(label,id,items){return `<div class="nav-item"><button class="nav-btn" data-nav="${id}">${label}${items?' <span class="caret">▼</span>':''}</button>${items?`<div class="dropdown">${items.map(x=>`<a class="drop-link" href="#${slug(x)}" data-route="${slug(x)}">${esc(x)}</a>`).join('')}</div>`:''}</div>`}
function slug(x){return x.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function bind(){
 document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{const p=b.parentElement;p.classList.toggle('open');document.querySelectorAll('.nav-item').forEach(x=>x!==p&&x.classList.remove('open'));});
 document.addEventListener('click',e=>{if(!e.target.closest('.nav-item'))document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('open'));});
 document.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();route(x.dataset.route);});
 document.getElementById('loginBtn').onclick=()=>loginModal();
 document.getElementById('searchInput').onkeydown=e=>{if(e.key==='Enter')search(e.target.value)};
 document.getElementById('prevMonth').onclick=()=>changeMonth(-1);document.getElementById('nextMonth').onclick=()=>changeMonth(1);
}
function renderNotices(page){const per=5,start=(page-1)*per;const rows=notices.slice(start,start+per);document.getElementById('noticeList').innerHTML=rows.map(n=>`<div class="notice-row"><div class="datebox"><span class="month">${n.month}</span><span class="day">${n.date}</span><span class="year">${n.year}</span></div><div class="notice-title">${esc(n.title)}</div><div class="notice-meta">${esc(n.meta)}</div><a class="pdf" href="${n.file}" target="_blank">PDF</a></div>`).join('');document.getElementById('pager').innerHTML='<button class="current">1</button><button>2</button><button>3</button>'}
function renderCalendar(){const items=[['21','AUG','Examination related activity'],['28','AUG','Admit Card / Candidate services'],['04','SEP','Recruitment examination'],['18','SEP','Answer key / result activity']];document.getElementById('calendarList').innerHTML=items.map(x=>`<div class="cal-row"><div class="cal-date"><strong>${x[0]}</strong><small>${x[1]}</small></div><div class="cal-name">${x[2]}</div></div>`).join('')}
function renderExams(){document.getElementById('examTrack').innerHTML=exams.slice(0,4).map(x=>`<article class="exam-card"><div><h3>${esc(x)}</h3><p>Notice, schedule and candidate information</p></div><span class="arrow">›</span></article>`).join('')}
function renderFaq(){document.getElementById('faqList').innerHTML=faqs.map((f,i)=>`<div class="faq-item"><button class="faq-q">${esc(f[0])}<span>＋</span></button><div class="faq-a">${esc(f[1])}</div></div>`).join('');document.querySelectorAll('.faq-q').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'))}
function loginModal(){modal(`<div class="modal small"><div class="modal-head"><h2>Candidate Login</h2><button class="close">×</button></div><div class="login-tabs"><button class="active">Candidate</button><button>Admin</button></div><div class="modal-body"><div class="form-group"><label>Registration Number</label><input placeholder="Enter registration number"></div><div class="form-group"><label>Password</label><input type="password" placeholder="Enter password"></div><div class="captcha"><span class="captcha-code">SSC 26</span><input placeholder="Enter captcha"></div><button class="primary" style="width:100%;margin-top:18px" onclick="toast('Demo login form — connect your authentication service here.')">Login</button><p style="text-align:center"><a class="link" href="#">Forgot Password?</a></p></div></div>`)}
function modal(html){const root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-backdrop">${html}</div>`;root.querySelector('.close').onclick=()=>root.innerHTML='';root.querySelector('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)root.innerHTML=''}}
function search(q){q=q.trim();if(!q)return;const hits=[...notices.map(n=>n.title),...exams].filter(x=>x.toLowerCase().includes(q.toLowerCase()));modal(`<div class="modal"><div class="modal-head"><h2>Search Results</h2><button class="close">×</button></div><div class="search-results">${hits.length?hits.map(x=>`<div class="search-item">${esc(x)}</div>`).join(''):'<p>No matching results found.</p>'}</div></div>`)}
function route(r){document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('open'));if(r==='result'||r==='admit'||r==='answer'||r==='apply'||r==='candidate-login'||r==='faq'||r==='exams'||r==='notices-all'||r==='calendar'){modal(`<div class="modal"><div class="modal-head"><h2>${esc(r.replace(/-/g,' ')).replace(/\b\w/g,m=>m.toUpperCase())}</h2><button class="close">×</button></div><div class="modal-body"><p>This service page is ready for connection to your SSC/Supabase data source.</p><div class="result-row"><b>Candidate service</b><span>Available online</span></div><div class="result-row"><b>Information</b><span>Official notices and links</span></div></div></div>`)}else document.getElementById(r)?.scrollIntoView({behavior:'smooth'});}
let calOffset=0;function changeMonth(n){calOffset+=n;const d=new Date(2026,7+calOffset,1);document.getElementById('calMonth').textContent=d.toLocaleString('en',{month:'long',year:'numeric'});}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}
shell();
