const A="assets/";
const notices=[
["Jul","24","2026","Sub Inspector in Delhi Police and CAPFs Examination, 2024:- Uploading Final Marks of candidates.","323.27 KB"],
["Jul","20","2026","Corrigendum for the post of Vocational Instructor under Selection Posts Examination.","87.66 KB"],
["Jul","16","2026","Grade 'C' Stenographers Limited Departmental Competitive Examination, 2025: Uploading of Tentative Answer Keys.","201.93 KB"],
["Jul","15","2026","Tentative vacancies of Senior Secretariat Assistant / UDC Grade Limited Departmental Competitive Examination, 2025.","421.09 KB"]
];
const exams=["Departmental Examination","Selection Posts Examination","Combined Graduate Level Examination, 2024","Stenographer Grade 'C' and 'D' Examination, 2024","Junior Engineer (Civil, Mechanical & Electrical) Examination","Combined Higher Secondary Level (10+2) Examination","Constable (GD) Examination","Combined Hindi Translators Examination","Sub-Inspector in Delhi Police and Central Armed Police Forces Examination","Others"];
const candidates=["SSC's Scribe Procedure","Script Evaluation","Examination Calendar","Scheme of Examination","Syllabus","Special Instruction","Previous Year Question Paper","Format of Certificates","Tentative Vacancy","Normalization Method","Mock Test"];
const about=["Background of Commission","Setup of Commission","Organisation Structure","Function of Commission","Vision, Mission & Objectives of SSC","Regional Network","Annual Report","Citizen's Charter","Contact List","Resolution","PIDPI","Right To Information","Committee on Sexual Harassment"];
const faqs=[
["Is Registration mandatory for applying to the examinations of the Commission?","Yes, One-Time Registration is a prerequisite for applying online."],
["I did not receive registration number and password on the email.","Check your Spam folder and contact the concerned Regional Office if necessary."],
["When is the notice/advertisement of an Examination issued?","Tentative dates are given in the Annual Calendar of Examinations."],
["What are the posts for which SSC conducts exams?","SSC conducts examinations for a wide range of Group B and Group C posts."],
["When does the Commission upload its Annual Calendar?","The Annual Calendar is uploaded as part of the Commission examination schedule."]
];
let lang="en";
const T=k=>({en:{home:"Home",chair:"Chairman’s Message",cand:"For Candidates",tender:"Tender",rti:"RTI",about:"About Us",login:"Login or Register",notice:"Notice Board",view:"View All",quick:"Quick Links",apply:"Apply",admit:"Admit Card",answer:"Answer Key",result:"Result",calendar:"SSC Calendar",browse:"Browse by Examinations",faq:"FAQs",other:"Other Initiatives"},hi:{home:"होम",chair:"अध्यक्ष का संदेश",cand:"उम्मीदवारों के लिए",tender:"निविदा",rti:"RTI",about:"हमारे बारे में",login:"लॉगिन या रजिस्टर",notice:"सूचना बोर्ड",view:"सभी देखें",quick:"त्वरित लिंक",apply:"आवेदन",admit:"प्रवेश पत्र",answer:"उत्तर कुंजी",result:"परिणाम",calendar:"SSC कैलेंडर",browse:"परीक्षाओं के अनुसार देखें",faq:"अक्सर पूछे जाने वाले प्रश्न",other:"अन्य पहल"})[lang][k]||k;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function nav(){return `<div class="topline"><span>Feedback | SSC Style Portal</span><span>Skip to Main Content | <button id="lang">${lang==="en"?"हिन्दी":"English"}</button> | +A A -A</span></div>
<div class="brandrow"><div class="brand"><div class="emblem">✦</div><div><b>Government of India</b><strong>STAFF SELECTION COMMISSION</strong></div></div><div class="actions"><input id="search" placeholder="Search"><button id="searchBtn">⌕</button><button id="loginBtn">${T("login")}</button></div></div>
<div class="nav"><div class="navinner">
<a data-page="home">${T("home")}</a><a data-page="chairman">${T("chair")}</a>${drop("For Candidates",candidates,"cand")}<a data-page="tender">${T("tender")}</a>${drop("RTI",["RTI- MIS","Proactive Disclosure (RTI)"],"rti")}${drop("About Us",about,"about")}
</div></div>`}
function drop(label,items,key){return `<div class="navdrop"><button>${T(key)} ▾</button><div class="dropdown">${items.map(x=>`<a data-item="${esc(x)}">${esc(x)}</a>`).join("")}</div></div>`}
function hero(){return `<div class="hero"><img id="hero" src="${A}hero-building-1.jpg"><button id="prev">‹</button><button id="next">›</button><div class="dots"><i class="on"></i><i></i><i></i></div></div>
<div class="ticker"><span>Follow the Staff Selection Commission on X (formerly Twitter): @SSC_GoI</span><span>One Time Registration (OTR) for Scribe is live. Please click here to register.</span><b>Join Indian Navy</b></div>`}
function noticesBlock(){return `<section class="section card"><header><h2>${T("notice")}</h2><a data-page="notices">${T("view")}</a></header><div>${notices.map((n,i)=>`<div class="notice"><div class="date"><b>${n[0]}</b><strong>${n[1]}</strong><small>${n[2]}</small></div><a data-notice="${i}">${esc(n[3])}</a><span>(${n[4]}) <em>PDF</em></span><button data-notice="${i}">◉</button></div>`).join("")}</div><div class="pager"><button>‹</button><button class="active">1</button><button>2</button><button>3</button><span>...</span><button>65</button><button>›</button></div></section>`}
function quick(){return `<section class="section"><h2>${T("quick")}</h2><div class="quick">${["Apply","Admit Card","Answer Key","Result"].map(x=>`<a data-quick="${x}"><span>${x==="Apply"?"✎":x==="Admit Card"?"▣":x==="Answer Key"?"▤":"▮"}</span>${T(x.toLowerCase().replace(" ",""))||x}</a>`).join("")}</div></section>`}
function calendar(){return `<section class="section card"><header><h2>${T("calendar")}</h2><span>Jul, 2026</span></header><div class="cal"><div><b>30</b><small>APR</small><span>Combined Hindi Translators Examination, 2026</span></div><div><b>31</b><small>MAY</small><span>Sub-Inspector in Delhi Police and Central Armed Police Forces Examination, 2026</span></div><div><b>5</b><small>JUN</small><span>Indian Navy Entrance Test (INET)</span></div></div><a class="view" data-page="calendar">${T("view")}</a></section>`}
function examsBlock(){return `<section class="exams"><div class="wrap"><div><h2>${T("browse")}</h2><p>Explore exam-related details and relevant resources</p></div><div class="examgrid">${exams.slice(0,4).map((x,i)=>`<a data-exam="${i}"><h3>${esc(x)}</h3><p>Explore exam-related details and relevant resources.</p><b>→</b></a>`).join("")}</div></div></section>`}
function faqBlock(){return `<section class="section faq"><div><h2>${T("faq")}</h2><p>List of common inquiries and their brief answers to provide quick information and assist users.</p><button class="primary" data-page="faqs">${T("view")}</button></div><div><label>MOST POPULAR FAQS</label>${faqs.map((f,i)=>`<div class="faqitem"><button data-faq="${i}">${esc(f[0])}<b>⊕</b></button><p>${esc(f[1])}</p></div>`).join("")}</div></section>`}
function initiatives(){return `<section class="section"><h2>${T("other")}</h2><div class="initiatives">${["Make in India","Incredible India","data.gov.in","Digital India"].map(x=>`<a data-init="${esc(x)}"><div class="initimg">${esc(x)}</div></a>`).join("")}</div></section>`}
function footer(){return `<footer><div><b>Staff Selection Commission</b><p>Public Disclosure of Scores and Other Details of Non-Recommended Willing Candidates</p><p>List of Debarred Candidates in Examinations Conducted by the Staff Selection Commission</p></div><div><b>Useful links</b><a>DoPT</a><a>Archives</a><a>Disclaimer</a><a>Sitemap</a><a>Help</a><a>Website Policies</a></div><div><b>Contact Us</b><p>Block No-12, CGO Complex, Lodhi Road<br>New Delhi - 110003</p></div><small>© 2026 SSC Style Portal — Unofficial</small></footer>`}
function home(){return nav()+hero()+`<main class="wrap">`+noticesBlock()+quick()+calendar()+examsBlock()+faqBlock()+initiatives()+`</main>`+footer()}
function page(title,body){return nav()+`<main class="wrap page"><div class="crumb">Homepage › ${esc(title)}</div><h1>${esc(title)}</h1>${body}</main>`+footer()}
function resultModal(){modal(`<h2>▮ Result <button class="x" data-close>×</button></h2><div class="tabs">${["All","CHSL","STENO","JE","CAPF","CTGD","CHT","OTHERS","DEPARTMENTAL EXAMS","DPHCM","RHQ","DPCE","CGL","DPCD","DPHCT","CEDP","MTS","STE"].map((x,i)=>`<button class="${i?"":"active"}">${x}</button>`).join("")}</div>${notices.slice(0,3).map(n=>`<div class="result"><span>${esc(n[3])}<small>03-08-2026</small></span><b>(${n[4]}) PDF<br><a>Write up</a> <a>Result</a></b></div>`).join("")}<button class="primary">View All</button>`)}
function admitModal(){modal(`<h2>▣ ${T("admit")} <button class="x" data-close>×</button></h2><div class="loginbox"><label>Username (Registration Number) *</label><input placeholder="Registration Number"><label>Password (SSC Registration Password) *</label><input type="password" placeholder="Password"><a>Forgot Password</a><div class="captcha">PBhCU</div><label>Captcha *</label><input placeholder="Captcha"><button class="primary">Login</button><p>New User? <a>Register Now</a></p></div>`)}
function applyModal(){modal(`<h2>✎ ${T("apply")} <button class="x" data-close>×</button></h2><div class="empty">Application is not active !</div>`)}
function answerModal(){modal(`<h2>▤ ${T("answer")} <button class="x" data-close>×</button></h2><div class="tabs">${["CGL","CHSL","JE","MTS","STENO","OTHERS"].map((x,i)=>`<button class="${i?"":"active"}">${x}</button>`).join("")}</div><div class="result">Tentative Answer Key and Response Sheet <b>PDF</b></div><div class="result">Final Answer Key and Response Sheet <b>PDF</b></div>`)}
function loginModal(){location.href="admin.html"}
function noticeModal(i){const n=notices[i];modal(`<h2>Notice <button class="x" data-close>×</button></h2><div class="noticeDetail"><div class="date">${n[0]} ${n[1]} ${n[2]}</div><p>${esc(n[3])}</p><p>PDF size: ${n[4]}</p><button class="primary">Download PDF</button></div>`)}
function modal(html){document.getElementById("modal-root").innerHTML=`<div class="back"><div class="modal">${html}</div></div>`;document.querySelector("[data-close]")?.addEventListener("click",()=>document.getElementById("modal-root").innerHTML="")}
function renderPage(){const root=document.getElementById("app");const h=location.hash.replace("#","");if(!h||h==="home")root.innerHTML=home();else if(h==="notices")root.innerHTML=page("Notice Board",noticesBlock());else if(h==="calendar")root.innerHTML=page("SSC Calendar",calendar());else if(h==="faqs")root.innerHTML=page("FAQs",`<div class="faq full">${faqs.concat(faqs).map((f,i)=>`<div class="faqitem"><button data-faq="${i%faqs.length}">${esc(f[0])}<b>⊕</b></button><p>${esc(f[1])}</p></div>`).join("")}</div>`);else if(h.startsWith("exam=")){const e=exams[+h.split("=")[1]]||exams[0];root.innerHTML=page(e,`<p>Explore exam-related details and relevant resources.</p><div class="quick"><a>Examination Notice</a><a>Syllabus</a><a>Previous Year Question Paper</a><a>Result</a></div>`)}else root.innerHTML=page(h.replace(/-/g," "),`<p>This section contains the selected SSC-style portal information and resources.</p>`);bind()}
function bind(){document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>{location.hash=x.dataset.page==="home"?"home":x.dataset.page});document.querySelectorAll("[data-exam]").forEach(x=>x.onclick=()=>location.hash="exam="+x.dataset.exam);document.querySelectorAll("[data-notice]").forEach(x=>x.onclick=()=>noticeModal(+x.dataset.notice));document.querySelectorAll("[data-quick]").forEach(x=>x.onclick=()=>({Result:resultModal,"Admit Card":admitModal,Apply:applyModal,"Answer Key":answerModal}[x.dataset.quick]||applyModal)());document.querySelectorAll("[data-faq]").forEach(x=>x.onclick=()=>x.parentElement.classList.toggle("open"));document.getElementById("loginBtn")?.addEventListener("click",loginModal);document.getElementById("lang")?.addEventListener("click",()=>{lang=lang==="en"?"hi":"en";renderPage()});document.querySelectorAll(".navdrop>button").forEach(b=>b.onclick=e=>{e.stopPropagation();b.parentElement.classList.toggle("open")});document.querySelectorAll("[data-item]").forEach(a=>a.onclick=e=>{e.preventDefault();location.hash=a.dataset.item.toLowerCase().replace(/[^a-z0-9]+/g,"-")});document.getElementById("searchBtn")?.addEventListener("click",()=>{const q=document.getElementById("search").value.trim().toLowerCase();if(q)modal(`<h2>Search <button class="x" data-close>×</button></h2><p>${esc([...notices.map(n=>n[3]),...exams,...faqs.map(f=>f[0])].filter(x=>x.toLowerCase().includes(q)).join("<br>")||"No matching results found.")}</p>`)});
let i=0;const img=document.getElementById("hero");if(img){const imgs=["hero-building-1.jpg","hero-building-2.jpg","hero-building-3.jpg"];const go=d=>{i=(i+d+imgs.length)%imgs.length;img.src=A+imgs[i]};document.getElementById("prev")?.addEventListener("click",()=>go(-1));document.getElementById("next")?.addEventListener("click",()=>go(1));setInterval(()=>go(1),5000)}}
addEventListener("hashchange",renderPage);renderPage();
