(() => {
'use strict';
let capturedDb=null;
const originalCreateClient=window.supabase?.createClient;
if(originalCreateClient&&!window.__sscPdfClientHooked){window.__sscPdfClientHooked=true;window.supabase.createClient=function(...args){capturedDb=originalCreateClient.apply(this,args);window.__sscPdfDb=capturedDb;return capturedDb;};}
const db=()=>capturedDb||window.__sscPdfDb;
const safe=v=>String(v??'').replace(/[^a-zA-Z0-9_-]/g,'_');
async function ctx(){const d=db();if(!d)return null;const s=await d.auth.getSession();const u=s.data?.session?.user;if(!u)return null;const r=await d.from('ssc_candidates').select('*').eq('user_id',u.id).maybeSingle();if(r.error)throw r.error;return{db:d,user:u,candidate:r.data||{}};}
async function img(url){try{const r=await fetch(url);if(!r.ok)return null;const b=await r.blob();return await new Promise(ok=>{const f=new FileReader();f.onload=()=>ok(f.result);f.onerror=()=>ok(null);f.readAsDataURL(b);});}catch(_){return null;}}
async function docImg(d,uid,type){try{const r=await d.from('ssc_candidate_documents').select('file_path,created_at').eq('candidate_id',uid).eq('document_type',type).order('created_at',{ascending:false}).limit(1);const p=r.data?.[0]?.file_path;if(!p)return null;const s=await d.storage.from('ssc-candidate-files').createSignedUrl(p,600);return s.data?.signedUrl?await img(s.data.signedUrl):null;}catch(_){return null;}}
async function qr(text){return img('https://api.qrserver.com/v1/create-qr-code/?size=180x180&data='+encodeURIComponent(text));}
function txt(doc,v,x,y,w){doc.setFont('helvetica','normal');doc.setFontSize(6.2);doc.text(String(v||'—'),x,y,{maxWidth:w});}
function box(doc,label,v,x,y,w,h=7){doc.rect(x,y,w,h);doc.setFont('helvetica','bold');doc.setFontSize(4.8);doc.text(label.toUpperCase(),x+1,y+2.5,{maxWidth:w-2});txt(doc,v,x+1,y+5.4,w-2);}
function section(doc,n,title,y){doc.setFillColor(235,235,235);doc.rect(12,y,186,5,'F');doc.setFont('helvetica','bold');doc.setFontSize(6.2);doc.text(n+'. '+title,14,y+3.5);return y+5;}
async function make(app){if(!window.jspdf?.jsPDF)throw Error('PDF library is not loaded.');const c=await ctx();if(!c)throw Error('Please login again.');const {db:d,user,candidate}=c,fd=app.form_data||{},edu=candidate.education_details||{};const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4',compress:true});
doc.setDrawColor(90);doc.setLineWidth(.4);doc.rect(8,7,194,282);doc.setTextColor(238,238,238);doc.setFont('helvetica','bold');doc.setFontSize(28);doc.text('STAFF SELECTION COMMISSION',105,150,{align:'center',angle:35});doc.setTextColor(0,0,0);
const photo=await docImg(d,user.id,'PHOTO'),signature=await docImg(d,user.id,'SIGNATURE'),q=await qr('SSC|'+(candidate.registration_no||'NA')+'|'+(app.application_no||app.id||'NA'));if(q)try{doc.addImage(q,'PNG',12,10,28,28,'qr','FAST');}catch(_){}if(photo)try{doc.addImage(photo,'JPEG',169,10,28,31,'photo','FAST');}catch(_){ }
doc.setFont('helvetica','bold');doc.setFontSize(9.2);doc.text('STAFF SELECTION COMMISSION',105,13,{align:'center'});doc.setFontSize(5.4);doc.text('BLOCK NO. 12, CGO-COMPLEX, LODHI ROAD, NEW DELHI 110003',105,17,{align:'center'});doc.setFontSize(7.4);doc.text(app.exam_name||'COMBINED GRADUATE LEVEL EXAMINATION',105,22,{align:'center'});doc.setFontSize(6.4);doc.text('ONLINE APPLICATION / CONFIRMATION',105,26,{align:'center'});doc.setFontSize(6.5);doc.text('REGISTRATION NO.: '+(candidate.registration_no||'Not Assigned'),105,31,{align:'center'});
let y=35;y=section(doc,1,'CANDIDATE / PERSONAL DETAILS',y);box(doc,'1. Candidate Name',candidate.full_name,12,y,47,12);box(doc,'2. New / Changed Name',candidate.changed_name||'—',59,y,47,12);box(doc,'3. Gender',candidate.gender||'—',106,y,45,12);box(doc,'4. Category',candidate.category,151,y,47,12);y+=12;box(doc,'5. Father Name',candidate.father_name,12,y,47,10);box(doc,'6. Mother Name',candidate.mother_name,59,y,47,10);box(doc,'7. Date of Birth',candidate.dob,106,y,45,10);box(doc,'8. Identification Mark',candidate.identification_mark,151,y,47,10);y+=10;box(doc,'9. Nationality',candidate.nationality||'Indian',12,y,47,10);box(doc,'10. Visible Identification Mark',candidate.identification_mark,59,y,94,10);box(doc,'11. PWD / Disability',candidate.pwd||'No',153,y,45,10);y+=10;box(doc,'12. Matriculation Board',edu.tenth_board,12,y,62,10);box(doc,'13. Matriculation Year',edu.tenth_year,74,y,62,10);box(doc,'14. Matriculation Roll No.',edu.tenth_roll||'—',136,y,62,10);y+=10;box(doc,'15. Correspondence Address',candidate.address,12,y,93,13);box(doc,'16. Permanent Address',candidate.permanent_address||candidate.address,105,y,93,13);y+=13;box(doc,'17. Mobile',candidate.phone,12,y,47,8);box(doc,'18. Email',candidate.email,59,y,47,8);box(doc,'19. City / State / PIN',(candidate.city||'')+' / '+(candidate.state||'')+' / '+(candidate.pincode||''),106,y,92,8);y+=8;
y=section(doc,2,'EXAMINATION / APPLICATION DETAILS',y);box(doc,'20. Examination',app.exam_name,12,y,93,9);box(doc,'21. Post',app.post_name,105,y,93,9);y+=9;box(doc,'22. Examination Centre / City',fd.centre,12,y,93,9);box(doc,'23. Application Status',app.status||'Submitted',105,y,93,9);y+=9;box(doc,'24. Application No.',app.application_no||app.id,12,y,62,9);box(doc,'25. Registration No.',candidate.registration_no,74,y,62,9);box(doc,'26. Submitted On',app.submitted_at?new Date(app.submitted_at).toLocaleString():'—',136,y,62,9);y+=9;
y=section(doc,3,'QUALIFICATION / OTHER DETAILS',y);box(doc,'27. Highest Qualification',edu.other||'—',12,y,62,9);box(doc,'28. Graduation University',edu.graduation_university,74,y,62,9);box(doc,'29. Graduation Year',edu.graduation_year,136,y,62,9);y+=9;box(doc,'30. 10th Marks / %',edu.tenth_marks,12,y,62,8);box(doc,'31. 12th Marks / %',edu.twelfth_marks,74,y,62,8);box(doc,'32. Graduation Marks / %',edu.graduation_marks,136,y,62,8);y+=8;box(doc,'33. Payment / Challan Status','See Challan / Payment section',12,y,93,8);box(doc,'34. Exam City Preference',fd.centre,105,y,93,8);y+=8;
y=section(doc,4,'DECLARATION',y);doc.rect(12,y,186,27);doc.setFont('helvetica','normal');doc.setFontSize(5.6);const declaration='I hereby declare that all statements made in this application are true, complete and correct to the best of my knowledge and belief. I understand that furnishing false information or suppressing material facts may result in cancellation of candidature and action under applicable rules.';doc.text(doc.splitTextToSize(declaration,178),15,y+6,{lineHeightFactor:1.35});doc.setFont('helvetica','bold');doc.setFontSize(5.5);doc.text('Date: '+new Date().toLocaleDateString(),15,y+23);doc.text('Candidate Signature',171,y+23,{align:'center'});if(signature)try{doc.addImage(signature,'JPEG',151,y+8,42,13,'sig','FAST');}catch(_){}y+=30;box(doc,'35. IP Address','—',12,y,62,8);box(doc,'36. Number of Attempts','1',74,y,62,8);box(doc,'37. PDF Generated',new Date().toLocaleString(),136,y,62,8);doc.setFontSize(5.2);doc.setFont('helvetica','normal');doc.text('System generated application confirmation. Please retain this document for future reference.',12,280);doc.text('Page 1 of 1',198,280,{align:'right'});doc.save('SSC_Application_'+safe(candidate.registration_no||app.application_no||app.id)+'.pdf');}
window.sscGenerateApplicationPdf=make;
async function getApp(id){const c=await ctx();if(!c)throw Error('Please login again.');const r=await c.db.from('ssc_applications').select('*').eq('id',id).eq('candidate_id',c.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data)throw Error('Application not found.');return r.data;}
async function download(id){try{const a=await getApp(id);await make(a);}catch(e){console.error(e);const t=document.getElementById('toast');if(t){t.textContent=e.message||'Unable to generate PDF.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000);}}}
function install(){document.addEventListener('click',e=>{const b=e.target.closest('[data-application-pdf]');if(b){e.preventDefault();download(b.dataset.applicationPdf);}},true);const f=document.getElementById('applicationForm');if(!f||f.dataset.sscPdfSubmitHooked)return;if(!db())return;f.dataset.sscPdfSubmitHooked='1';f.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const d=db(),s=await d.auth.getSession(),u=s.data?.session?.user;if(!u)return;const exam=document.getElementById('aExam')?.value.trim()||'',post=document.getElementById('aPost')?.value.trim()||null,centre=document.getElementById('aCentre')?.value.trim()||'';if(!exam||!centre)return;const id=document.getElementById('aId')?.value||'';const payload={exam_name:exam,post_name:post,status:'submitted',submitted_at:new Date().toISOString(),form_data:{centre},updated_at:new Date().toISOString()};const r=id?await d.from('ssc_applications').update(payload).eq('id',id).eq('candidate_id',u.id).select().single():await d.from('ssc_applications').insert({...payload,candidate_id:u.id}).select().single();if(r.error){console.error(r.error);return;}f.hidden=true;try{await make(r.data);}catch(x){console.error(x);}setTimeout(()=>location.reload(),700);},true);}
window.addEventListener('DOMContentLoaded',()=>setTimeout(install,500));setInterval(()=>{if(db())install();},700);
})();