const cfg=window.SSC_CONFIG||{};
const db=(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase)?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id);
let me=null, profile=null, applications=[], results=[], payments=[], messages=[], docs=[];
const msg=(id,t)=>$(id).textContent=t;
function show(id,on=true){$(id).classList.toggle('hidden',!on)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function init(){if(!db){msg('authMsg','Supabase is not configured.');return}const {data}=await db.auth.getSession();if(data.session){me=data.session.user;await dashboard()}else show('loginView')}
$('login').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||!password){msg('authMsg','Enter email and password.');return}const {data,error}=await db.auth.signInWithPassword({email,password});if(error){msg('authMsg',error.message);return}me=data.user;await dashboard()};
$('register').onclick=()=>{show('loginView',false);show('registerView')};
$('backLogin').onclick=()=>{show('registerView',false);show('loginView')};
$('doRegister').onclick=async()=>{const email=$('regEmail').value.trim(),password=$('regPassword').value,registration_no=$('regNo').value.trim(),full_name=$('regName').value.trim();if(!email||password.length<8||!registration_no||!full_name){msg('regMsg','Email, password (8+), registration number and name are required.');return}const {data,error}=await db.auth.signUp({email,password});if(error){msg('regMsg',error.message);return}if(!data.user){msg('regMsg','Registration could not be completed.');return}const {error:pe}=await db.from('ssc_candidates').insert({user_id:data.user.id,registration_no,full_name,email});if(pe){msg('regMsg',pe.message);return}msg('regMsg','Account created. If email confirmation is enabled, confirm your email then login.');show('registerView',false);show('loginView')};
$('forgot').onclick=async()=>{const email=$('email').value.trim();if(!email){msg('authMsg','Enter your email first.');return}const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.href});msg('authMsg',error?error.message:'Password reset link sent. Check your email.')};
$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden')});
async function dashboard(){show('loginView',false);show('registerView',false);show('dashboard');show('logout');const p=await db.from('ssc_candidates').select('*').eq('user_id',me.id).maybeSingle();profile=p.data;if(p.error||!profile){msg('welcome','Candidate profile not found. Ask admin to create/restore your profile.');return}fillProfile();await loadAll();msg('welcome',`Welcome, ${profile.full_name}. Your published information is shown below.`)}
function fillProfile(){$('pName').value=profile.full_name||'';$('pReg').value=profile.registration_no||'';$('pRoll').value=profile.roll_no||'';$('pPhone').value=profile.phone||'';$('pDob').value=profile.dob||'';$('pCategory').value=profile.category||'';$('pFather').value=profile.father_name||'';$('pMother').value=profile.mother_name||'';$('pAddress').value=profile.address||'';$('pCity').value=profile.city||'';$('pState').value=profile.state||'';$('pPin').value=profile.pincode||'';$('sReg').textContent=profile.registration_no||'—';$('sRoll').textContent=profile.roll_no||'—'}
$('saveProfile').onclick=async()=>{const patch={full_name:$('pName').value.trim(),roll_no:$('pRoll').value.trim()||null,phone:$('pPhone').value.trim()||null,dob:$('pDob').value||null,category:$('pCategory').value.trim()||null,father_name:$('pFather').value.trim()||null,mother_name:$('pMother').value.trim()||null,address:$('pAddress').value.trim()||null,city:$('pCity').value.trim()||null,state:$('pState').value.trim()||null,pincode:$('pPin').value.trim()||null,updated_at:new Date().toISOString()};const {data,error}=await db.from('ssc_candidates').update(patch).eq('user_id',me.id).select().single();msg('profileMsg',error?error.message:'Details saved.');if(data){profile=data;fillProfile()}}
async function loadAll(){const [a,r,p,d,m]=await Promise.all([db.from('ssc_applications').select('*').eq('candidate_id',me.id).order('created_at',{ascending:false}),db.from('ssc_results').select('*').eq('candidate_id',me.id).eq('published',true).order('created_at',{ascending:false}),db.from('ssc_payments').select('*').eq('candidate_id',me.id).order('created_at',{ascending:false}),db.from('ssc_candidate_documents').select('*').eq('candidate_id',me.id).order('created_at',{ascending:false}),db.from('ssc_candidate_messages').select('*').eq('candidate_id',me.id).eq('published',true).order('created_at',{ascending:false})]);applications=a.data||[];results=r.data||[];payments=p.data||[];docs=d.data||[];messages=m.data||[];renderAll()}
function renderAll(){$('sApp').textContent=applications[0]?.status||'—';$('sResult').textContent=results[0]?.selection_status||'—';$('appList').innerHTML=applications.length?applications.map(x=>`<div class="item"><div class="item-head"><b>${esc(x.exam_name)}${x.post_name?' — '+esc(x.post_name):''}</b><span class="badge">${esc(x.status)}</span></div><p class="muted">${esc(x.application_no||'Application number pending')}</p></div>`).join(''):'<div class="muted">No applications yet.</div>';$('resultList').innerHTML=results.length?results.map(x=>`<div class="item"><b>${esc(x.exam_name)}</b><p>${esc(x.post_name||'')} · Marks: <b>${esc(x.marks??'—')}</b> / ${esc(x.max_marks??'—')}</p><p>Selection: <b>${esc(x.selection_status||'—')}</b> · Rank: ${esc(x.rank||'—')}</p><p class="muted">${esc(x.remarks||'')}</p></div>`).join(''):'<div class="muted">No published result yet.</div>';$('paymentList').innerHTML=payments.length?payments.map(x=>`<div class="item"><b>₹${esc(x.amount)}</b> · <span class="badge">${esc(x.status)}</span><p>Challan: ${esc(x.challan_no||'—')} · Ref: ${esc(x.transaction_ref||'—')}</p></div>`).join(''):'<div class="muted">No payment/challan record yet.</div>';$('docList').innerHTML=(docs.length?docs.map(x=>`<div class="item"><b>${esc(x.document_type)}</b> · ${esc(x.title||'Document')} ${x.verified?'<span class="badge">Verified</span>':''}</div>`).join(''):'<div class="muted">No documents uploaded.</div>');$('messageList').innerHTML=messages.length?messages.map(x=>`<div class="item notice"><b>${esc(x.title)}</b><p>${esc(x.body||'')}</p></div>`).join(''):'<div class="muted">No messages.</div>'}
$('newApp').onclick=()=>show('appForm');
$('saveApp').onclick=async()=>{const {error}=await db.from('ssc_applications').insert({candidate_id:me.id,exam_name:$('aExam').value,post_name:$('aPost').value.trim()||null,status:'Draft',form_data:{details:$('aData').value}});if(error)alert(error.message);else{show('appForm',false);await loadAll()}};
$('uploadDoc').onclick=async()=>{const f=$('docFile').files[0];if(!f)return alert('Choose a document.');const path=`${me.id}/documents/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await db.storage.from('ssc-candidate-files').upload(path,f,{upsert:false,contentType:f.type||'application/octet-stream'});if(up.error)return alert(up.error.message);const ins=await db.from('ssc_candidate_documents').insert({candidate_id:me.id,document_type:$('docType').value,title:f.name,file_path:path});if(ins.error)alert(ins.error.message);else await loadAll()};
init();