(() => {
  'use strict';
  const cfg = window.SSC_CONFIG || {};
  const db = (cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && window.supabase)
    ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY, { auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true} }) : null;
  const $=id=>document.getElementById(id);
  let currentUser=null,currentCandidate=null,busy=false;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const msg=(t,ok=false)=>{const e=$('authMsg');if(e){e.textContent=t||'';e.style.color=ok?'#27865b':'#9a4448';}};
  const toast=t=>{const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__sscToast);window.__sscToast=setTimeout(()=>e.classList.remove('show'),2800)};
  const busyForm=(f,on,label)=>{busy=on;const b=f?.querySelector('button[type="submit"]');if(!b)return;if(on){b.dataset.old=b.textContent;b.textContent=label||'Please wait…';b.disabled=true}else{b.textContent=b.dataset.old||b.textContent;b.disabled=false}};
  function switchAuth(type,clear=true){document.querySelectorAll('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===type));if($('loginForm'))$('loginForm').hidden=type!=='login';if($('signupForm'))$('signupForm').hidden=type!=='signup';if(clear)msg('');(type==='signup'?$('signupName'):$('loginIdentifier'))?.focus()}
  async function session(){if(!db)return null;const r=await db.auth.getSession();if(r.error)throw r.error;return r.data?.session||null}
  async function loadCandidate(){if(!db||!currentUser)return null;const r=await db.from('ssc_candidates').select('*').eq('user_id',currentUser.id).maybeSingle();if(r.error)throw r.error;currentCandidate=r.data;return currentCandidate}
  async function createCandidate(){if(!db||!currentUser)return null;const found=await loadCandidate();if(found)return found;const name=currentUser.user_metadata?.full_name||'Candidate',phone=currentUser.user_metadata?.phone||null;const r=await db.from('ssc_candidates').insert({user_id:currentUser.id,registration_no:null,roll_no:null,full_name:name,email:currentUser.email||'',phone,status:'Pending',education_details:{}}).select().single();if(r.error)throw r.error;currentCandidate=r.data;return currentCandidate}
  async function login(e){e.preventDefault();if(busy)return;if(!db)return msg('Supabase configuration is missing.');const id=$('loginIdentifier')?.value.trim()||'',pw=$('loginPassword')?.value||'';if(!id||!pw)return msg('Enter Registration No. or Email and password.');busyForm(e.currentTarget,true,'Signing in…');msg('Signing in…',true);try{let email=id;if(!id.includes('@')){const rr=await fetch(`${cfg.SUPABASE_URL}/functions/v1/ssc-candidate-login-by-registration`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.SUPABASE_ANON_KEY},body:JSON.stringify({registration_no:id,password:pw})});const out=await rr.json().catch(()=>({}));if(!rr.ok||!out.session)throw new Error(out.error||'Invalid registration number or password.');const sr=await db.auth.setSession({access_token:out.session.access_token,refresh_token:out.session.refresh_token});if(sr.error)throw sr.error;currentUser=sr.data.user;await loadCandidate();await openPortal()}else{const r=await db.auth.signInWithPassword({email,password:pw});if(r.error)throw r.error;currentUser=r.data.user;await createCandidate();await openPortal()}}catch(err){console.error(err);msg(/invalid login credentials/i.test(err?.message||'')?'Registration No. or email, or password is incorrect.':err?.message||String(err))}finally{busyForm(e.currentTarget,false)}}
  async function signup(e){e.preventDefault();if(busy)return;if(!db)return msg('Supabase configuration is missing.');const f=e.currentTarget,name=$('signupName')?.value.trim()||'',email=$('signupEmail')?.value.trim()||'',phone=$('signupPhone')?.value.trim()||'',pw=$('signupPassword')?.value||'';if(!name||!email)return msg('Enter your name and email.');if(pw.length<6)return msg('Password must be at least 6 characters.');busyForm(f,true,'Creating account…');try{const redirect=new URL('candidate.html',location.href).href;const rr=await fetch(`${cfg.SUPABASE_URL}/functions/v1/ssc-candidate-register`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.SUPABASE_ANON_KEY},body:JSON.stringify({name,email,phone,password:pw})});const out=await rr.json().catch(()=>({}));if(!rr.ok)throw new Error(out.error||'Registration failed.');if(out.session){const sr=await db.auth.setSession({access_token:out.session.access_token,refresh_token:out.session.refresh_token});if(sr.error)throw sr.error;currentUser=sr.data.user;currentCandidate=out.candidate||null;await openPortal()}else{switchAuth('login',false);$('loginIdentifier').value=email;msg(out.message||'Account created. Login with your email and password.',true)}}catch(err){msg(/already registered|already exists/i.test(err?.message||'')?'This email is already registered. Please login.':err?.message||String(err))}finally{busyForm(f,false)}}
  async function forgot(){if(!db)return;const email=prompt('Enter your registered email address');if(!email?.trim())return;const r=await db.auth.resetPasswordForEmail(email.trim(),{redirectTo:new URL('candidate.html?mode=login',location.href).href});msg(r.error?r.error.message:'Password reset email sent. Check your inbox.',!r.error)}
  async function changePassword(){if(!db)return;const pw=prompt('Enter your new password (minimum 6 characters)');if(!pw)return;if(pw.length<6)return toast('Password must be at least 6 characters.');const r=await db.auth.updateUser({password:pw});if(r.error)return toast(r.error.message);toast('Password changed successfully.')}
  function fillProfile(){const c=currentCandidate||{};const vals={pName:c.full_name,pEmail:c.email,pPhone:c.phone,pDob:c.dob,pFather:c.father_name,pMother:c.mother_name,pCategory:c.category,pAddress:c.address,pCity:c.city,pState:c.state,pPincode:c.pincode};Object.entries(vals).forEach(([id,v])=>{if($(id))$(id).value=v||''});if($('profileStatus'))$('profileStatus').textContent=c.status||'Pending';if($('regLine'))$('regLine').textContent=c.registration_no?'Registration No: '+c.registration_no:'Registration No.: Not yet assigned by Admin';if($('assignedReg'))$('assignedReg').textContent=c.registration_no||'Not assigned';if($('assignedRoll'))$('assignedRoll').textContent=c.roll_no||'Not assigned'}
  async function saveProfile(e){e.preventDefault();if(!currentUser||!db)return toast('Please login again.');const p={full_name:$('pName').value.trim(),phone:$('pPhone').value.trim()||null,dob:$('pDob').value||null,father_name:$('pFather').value.trim()||null,mother_name:$('pMother').value.trim()||null,category:$('pCategory').value||null,address:$('pAddress').value.trim()||null,city:$('pCity').value.trim()||null,state:$('pState').value.trim()||null,pincode:$('pPincode').value.trim()||null,updated_at:new Date().toISOString()};const r=await db.from('ssc_candidates').update(p).eq('user_id',currentUser.id);if(r.error)return toast(r.error.message);currentCandidate={...currentCandidate,...p};fillProfile();toast('Personal details saved.')}
  function education(){return {tenth_board:$('edu10Board')?.value.trim()||'',tenth_year:$('edu10Year')?.value.trim()||'',tenth_marks:$('edu10Marks')?.value.trim()||'',twelfth_board:$('edu12Board')?.value.trim()||'',twelfth_year:$('edu12Year')?.value.trim()||'',twelfth_marks:$('edu12Marks')?.value.trim()||'',graduation_university:$('eduGradUni')?.value.trim()||'',graduation_year:$('eduGradYear')?.value.trim()||'',graduation_marks:$('eduGradMarks')?.value.trim()||'',other:$('eduOther')?.value.trim()||''}}
  function fillEducation(){const d=currentCandidate?.education_details||{};[['edu10Board','tenth_board'],['edu10Year','tenth_year'],['edu10Marks','tenth_marks'],['edu12Board','twelfth_board'],['edu12Year','twelfth_year'],['edu12Marks','twelfth_marks'],['eduGradUni','graduation_university'],['eduGradYear','graduation_year'],['eduGradMarks','graduation_marks'],['eduOther','other']].forEach(([id,k])=>{if($(id))$(id).value=d[k]||''})}
  async function saveEducation(e){e.preventDefault();const r=await db.from('ssc_candidates').update({education_details:education(),updated_at:new Date().toISOString()}).eq('user_id',currentUser.id);if(r.error)return toast(r.error.message);currentCandidate.education_details=education();toast('Educational details saved.')}
  async function applications(){const el=$('applicationList');if(!el||!currentUser)return;const r=await db.from('ssc_applications').select('*').eq('candidate_id',currentUser.id).order('created_at',{ascending:false});if(r.error){el.innerHTML='<div class="item">'+esc(r.error.message)+'</div>';return}el.innerHTML=(r.data||[]).map(n=>{const f=n.form_data||{};const pdf=n.status==='submitted'?`<button type="button" class="outline" data-application-pdf="${esc(n.id)}">Download Application PDF</button>`:'';return `<article class="item"><div class="itemhead"><div><h3>${esc(n.exam_name)}</h3><div class="meta">Post: ${esc(n.post_name||'—')} · Application: ${esc(n.application_no||'—')}</div></div><span class="pill">${esc(n.status||'Draft')}</span></div><div class="meta">Qualification: ${esc(f.qualification||'—')} · Year: ${esc(f.year||'—')} · Centre: ${esc(f.centre||'—')}</div><div class="actions" style="margin-top:10px">${pdf}</div></article>`}).join('')||'<div class="item">No applications yet.</div>'}
  async function saveApplication(e){e.preventDefault();const form_data={qualification:$('aQualification').value.trim(),year:$('aYear').value.trim(),board:$('aBoard').value.trim(),percentage:$('aPercentage').value.trim(),centre:$('aCentre').value.trim(),additional:$('aAdditional').value.trim()};const id=$('aId').value;const payload={exam_name:$('aExam').value.trim(),post_name:$('aPost').value.trim()||null,status:'submitted',submitted_at:new Date().toISOString(),form_data,updated_at:new Date().toISOString()};const r=id?await db.from('ssc_applications').update(payload).eq('id',id).eq('candidate_id',currentUser.id):await db.from('ssc_applications').insert({...payload,candidate_id:currentUser.id});if(r.error)return toast(r.error.message);$('applicationForm').hidden=true;await applications();toast('Application submitted. PDF is being generated…')}
  async function documents(){const el=$('documentList');if(!el||!currentUser)return;const r=await db.from('ssc_candidate_documents').select('*').eq('candidate_id',currentUser.id).order('created_at',{ascending:false});if(r.error){el.innerHTML='<div class="item">'+esc(r.error.message)+'</div>';return}el.innerHTML=(r.data||[]).map(n=>`<article class="item"><div class="itemhead"><div><h3>${esc(n.title||n.document_type)}</h3><div class="meta">${esc(n.document_type)} · ${n.verified?'Verified':'Pending verification'}</div></div><span class="pill">${n.verified?'Verified':'Pending'}</span></div><a href="#" data-doc="${esc(n.file_path)}">Open document</a></article>`).join('')||'<div class="item">No documents uploaded.</div>';document.querySelectorAll('[data-doc]').forEach(a=>a.onclick=async e=>{e.preventDefault();const x=await db.storage.from('ssc-candidate-files').createSignedUrl(a.dataset.doc,300);if(x.error)return toast(x.error.message);window.open(x.data.signedUrl,'_blank','noopener')})}
  async function uploadDocument(e){e.preventDefault();const file=$('docFile')?.files?.[0];if(!file||!currentUser)return toast('Choose a document first.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${currentUser.id}/${Date.now()}-${safe}`;$('docMsg').textContent='Uploading…';const u=await db.storage.from('ssc-candidate-files').upload(path,await file.arrayBuffer(),{contentType:file.type||'application/octet-stream',upsert:false});if(u.error)return $('docMsg').textContent=u.error.message;const r=await db.from('ssc_candidate_documents').insert({candidate_id:currentUser.id,document_type:$('docType').value,title:$('docTitle').value.trim()||file.name,file_path:path,verified:false});if(r.error){await db.storage.from('ssc-candidate-files').remove([path]);return $('docMsg').textContent=r.error.message}$('docMsg').textContent='Upload successful.';$('docFile').value='';$('docTitle').value='';await documents()}
  async function results(){const el=$('resultList');if(!el||!currentUser)return;const r=await db.from('ssc_results').select('*').eq('candidate_id',currentUser.id).eq('published',true).order('result_date',{ascending:false});if(r.error)return el.innerHTML='<div class="item">'+esc(r.error.message)+'</div>';el.innerHTML=(r.data||[]).map(n=>`<article class="item"><div class="itemhead"><div><h3>${esc(n.exam_name||n.title||'Result')}</h3><div class="meta">${esc(n.result_date||'')}</div></div><span class="pill">${esc(n.selection_status||'Published')}</span></div><div class="meta">Post: ${esc(n.post_name||'—')} · Marks: ${esc(n.marks??'—')}/${esc(n.max_marks??'—')} · Rank: ${esc(n.rank||'—')}</div><p>${esc(n.remarks||'')}</p></article>`).join('')||'<div class="item">No published result is available.</div>'}
  async function payments(){const el=$('paymentList');if(!el||!currentUser)return;const r=await db.from('ssc_payments').select('*').eq('candidate_id',currentUser.id).order('created_at',{ascending:false});if(r.error)return el.innerHTML='<div class="item">'+esc(r.error.message)+'</div>';el.innerHTML=(r.data||[]).map(n=>`<article class="item"><b>Challan: ${esc(n.challan_no||'—')}</b><div class="meta">Amount: ₹${esc(n.amount||0)} · Status: ${esc(n.status||'Pending')} · Ref: ${esc(n.transaction_ref||'—')}</div></article>`).join('')||'<div class="item">No challan/payment record available.</div>'}
  async function admitCards(){const el=$('admitList');if(!el||!currentUser)return;const r=await db.from('ssc_admit_cards').select('*').eq('candidate_id',currentUser.id).eq('published',true).order('exam_date',{ascending:false});if(r.error)return el.innerHTML='<div class="item">'+esc(r.error.message)+'</div>';el.innerHTML=(r.data||[]).map(n=>`<article class="item"><h3>${esc(n.exam_name)}</h3><div class="meta">Post: ${esc(n.post_name||'—')} · Exam: ${esc(n.exam_date||'—')} · Time: ${esc(n.exam_time||'—')} · Reporting: ${esc(n.reporting_time||'—')}</div><p>Venue: ${esc(n.venue||'—')}</p>${n.file_path?`<a target="_blank" href="${esc(n.file_path)}">Download Admit Card</a>`:''}</article>`).join('')||'<div class="item">No admit card has been published by Admin.</div>'}
  async function answerKeys(){const el=$('answerList');if(!el||!currentUser)return;const r=await db.from('ssc_answer_keys').select('*').eq('candidate_id',currentUser.id).eq('published',true).order('created_at',{ascending:false});if(r.error)return el.innerHTML='<div class="item">'+esc(r.error.message)+'</div>';el.innerHTML=(r.data||[]).map(n=>`<article class="item"><h3>${esc(n.title||n.exam_name)}</h3><div class="meta">${esc(n.post_name||'')}</div>${n.file_path?`<a target="_blank" href="${esc(n.file_path)}">Open Answer Key</a>`:''}</article>`).join('')||'<div class="item">No published answer key is available.</div>'}
  async function messages(){const el=$('messageList');if(!el||!currentUser)return;const r=await db.from('ssc_candidate_messages').select('*').eq('candidate_id',currentUser.id).eq('published',true).order('created_at',{ascending:false});if(r.error)return el.innerHTML='<div class="item">'+esc(r.error.message)+'</div>';el.innerHTML=(r.data||[]).map(n=>`<article class="item"><h3>${esc(n.title)}</h3><div class="meta">${esc(new Date(n.created_at).toLocaleString())}</div><p>${esc(n.body||'')}</p></article>`).join('')||'<div class="item">No messages.</div>'}
  async function openPortal(){if(!currentCandidate)await createCandidate();$('authCard').hidden=true;$('portal').hidden=false;$('welcome').textContent='Welcome, '+(currentCandidate.full_name||'Candidate');fillProfile();fillEducation();await Promise.allSettled([applications(),results(),documents(),messages(),payments(),admitCards(),answerKeys()])}
  async function logout(){try{await db?.auth.signOut()}finally{location.reload()}}
  function bind(){document.querySelectorAll('[data-auth]').forEach(b=>b.addEventListener('click',()=>switchAuth(b.dataset.auth)));$('loginForm')?.addEventListener('submit',login);$('signupForm')?.addEventListener('submit',signup);$('forgotBtn')?.addEventListener('click',forgot);$('changePassword')?.addEventListener('click',changePassword);$('logout')?.addEventListener('click',logout);$('profileForm')?.addEventListener('submit',saveProfile);$('educationForm')?.addEventListener('submit',saveEducation);$('newApplication')?.addEventListener('click',()=>{$('applicationForm').hidden=false;$('aId').value=''});$('cancelApplication')?.addEventListener('click',()=>{$('applicationForm').hidden=true});$('applicationForm')?.addEventListener('submit',saveApplication);$('docForm')?.addEventListener('submit',uploadDocument);document.querySelectorAll('.sidebtn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.sidebtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.hidden=true);$(b.dataset.section).hidden=false}));const mode=new URLSearchParams(location.search).get('mode');switchAuth(mode==='signup'||mode==='register'?'signup':'login',false)}
  window.addEventListener('DOMContentLoaded',async()=>{bind();if(!db)return msg('Supabase configuration is missing.');try{const s=await session();if(s?.user){currentUser=s.user;await createCandidate();await openPortal()}}catch(e){console.error(e);msg(e?.message||String(e))}})
})();
