const cfg=window.SSC_CONFIG||{};const db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const $=id=>document.getElementById(id);let adminUser=null,current=null;function show(id,on=true){$(id).classList.toggle('hidden',!on)}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function init(){const {data}=await db.auth.getSession();if(data.session){adminUser=data.session.user;const ok=await isAdmin();if(ok){show('login',false);show('manager')}else alert('Admin access required.')}}async function isAdmin(){const {data}=await db.from('ssc_admins').select('user_id').eq('user_id',adminUser.id).maybeSingle();return !!data}
$('doLogin').onclick=async()=>{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return $('loginMsg').textContent=error.message;adminUser=data.user;if(!await isAdmin()){await db.auth.signOut();return $('loginMsg').textContent='Admin access required.'}show('login',false);show('manager')};
$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};
$('createCandidate').onclick=async()=>{const body={email:$('cEmail').value.trim(),password:$('cPassword').value,registration_no:$('cReg').value.trim(),full_name:$('cName').value.trim(),roll_no:$('cRoll').value.trim(),phone:$('cPhone').value.trim(),dob:$('cDob').value||null,category:$('cCategory').value.trim(),father_name:$('cFather').value.trim(),mother_name:$('cMother').value.trim(),state:$('cState').value.trim(),city:$('cCity').value.trim(),pincode:$('cPin').value.trim(),address:$('cAddress').value.trim()};const {data:{session}}=await db.auth.getSession();const res=await fetch(`${cfg.SUPABASE_URL}/functions/v1/ssc-admin-create-candidate`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:cfg.SUPABASE_ANON_KEY},body:JSON.stringify(body)});const out=await res.json();$('createMsg').textContent=out.error||`Candidate created: ${out.registration_no}`};
$('find').onclick=async()=>{const q=$('search').value.trim();if(!q)return;const {data,error}=await db.from('ssc_candidates').select('*').or(`registration_no.ilike.%${q}%,email.ilike.%${q}%,full_name.ilike.%${q}%`).limit(20);if(error)return $('candidateList').textContent=error.message;$('candidateList').innerHTML=(data||[]).map(x=>`<p><button data-id="${x.user_id}">${esc(x.registration_no)} — ${esc(x.full_name)}</button></p>`).join('')||'No candidates found';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>edit(b.dataset.id))};
async function edit(id){const {data,error}=await db.from('ssc_candidates').select('*').eq('user_id',id).single();if(error)return $('editMsg').textContent=error.message;current=data;show('editor');$('editName').textContent=`${data.full_name} · ${data.registration_no}`;for(const [id,k] of Object.entries({eId:'user_id',eReg:'registration_no',eRoll:'roll_no',eName:'full_name',ePhone:'phone',eDob:'dob',eCategory:'category',eFather:'father_name',eMother:'mother_name',eState:'state',eCity:'city',ePin:'pincode',eStatus:'status',eAddress:'address'}))$(id).value=data[k]||''}
$('saveCandidate').onclick=async()=>{const patch={registration_no:$('eReg').value.trim(),roll_no:$('eRoll').value.trim()||null,full_name:$('eName').value.trim(),phone:$('ePhone').value.trim()||null,dob:$('eDob').value||null,category:$('eCategory').value.trim()||null,father_name:$('eFather').value.trim()||null,mother_name:$('eMother').value.trim()||null,state:$('eState').value.trim()||null,city:$('eCity').value.trim()||null,pincode:$('ePin').value.trim()||null,status:$('eStatus').value.trim()||'Active',address:$('eAddress').value.trim()||null,updated_at:new Date().toISOString()};const {error}=await db.from('ssc_candidates').update(patch).eq('user_id',current.user_id);$('editMsg').textContent=error?error.message:'Candidate details saved.';if(!error)current={...current,...patch}};
async function sendCandidateEmail(to,subject,text){try{const {data:{session}}=await db.auth.getSession();if(!session)return;const r=await fetch(`${cfg.SUPABASE_URL}/functions/v1/ssc-send-candidate-email`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:cfg.SUPABASE_ANON_KEY},body:JSON.stringify({to,subject,text})});const out=await r.json().catch(()=>({}));if(!r.ok) $('editMsg').textContent += ` Email: ${out.error||'not configured'}`;}catch(e){$('editMsg').textContent += ` Email: ${e.message}`;}}
$('saveResult').onclick=async()=>{const {error}=await db.from('ssc_results').insert({candidate_id:current.user_id,exam_name:$('rExam').value.trim(),post_name:$('rPost').value.trim()||null,marks:$('rMarks').value||null,max_marks:$('rMax').value||null,rank:$('rRank').value.trim()||null,selection_status:$('rSelection').value.trim()||null,result_date:$('rDate').value||null,remarks:$('rRemarks').value.trim()||null,published:$('rPublish').checked});if(error){$('editMsg').textContent=error.message;return} $('editMsg').textContent='Result saved.'; await sendCandidateEmail(current.email,'SSC Portal – Result/Selection Update',`Your result/selection information has been updated. Login to your Candidate Portal to view the published details.`);
$('saveMessage').onclick=async()=>{const {error}=await db.from('ssc_candidate_messages').insert({candidate_id:current.user_id,title:$('mTitle').value.trim(),body:$('mBody').value.trim(),published:true});if(error){$('editMsg').textContent=error.message;return} $('editMsg').textContent='Message published.'; await sendCandidateEmail(current.email,$('mTitle').value.trim()||'SSC Portal Notification',$('mBody').value.trim()||'A new message has been published in your Candidate Portal.');
init();