const cfg=window.SSC_CONFIG||{};
const db=(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase)?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id);
let currentUser=null,currentCandidate=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=(text,good=false)=>{if($('authMsg'))$('authMsg').textContent=text;if(good)toast(text)};
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function registration(){return 'SSC'+new Date().getFullYear()+Date.now().toString().slice(-8)}
async function session(){if(!db)return null;const r=await db.auth.getSession();return r.data?.session||null}
async function ensureCandidate(){
  if(!currentUser)return;
  let r=await db.from('ssc_candidates').select('*').eq('user_id',currentUser.id).maybeSingle();
  if(r.data){currentCandidate=r.data;return}
  const name=$('signupName')?.value.trim()||currentUser.user_metadata?.full_name||'Candidate';
  const email=currentUser.email||'';
  const ins=await db.from('ssc_candidates').insert({user_id:currentUser.id,registration_no:registration(),full_name:name,email,phone:$('signupPhone')?.value.trim()||null,status:'Active'}).select().single();
  if(ins.error){msg(ins.error.message);return}
  currentCandidate=ins.data;
}
function switchAuth(type){document.querySelectorAll('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===type));$('loginForm').hidden=type!=='login';$('signupForm').hidden=type!=='signup';$('authMsg').textContent=''}
document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>switchAuth(b.dataset.auth));
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!db)return msg('Supabase configuration is missing.');const r=await db.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(r.error)return msg(r.error.message);currentUser=r.data.user;await ensureCandidate();await openPortal()};
$('signupForm').onsubmit=async e=>{e.preventDefault();if(!db)return msg('Supabase configuration is missing.');const email=$('signupEmail').value.trim(),password=$('signupPassword').value,name=$('signupName').value.trim();const r=await db.auth.signUp({email,password,options:{data:{full_name:name}}});if(r.error)return msg(r.error.message);if(!r.data.user)return msg('Account created. Check your email to confirm, then login.');if(!r.data.session){return msg('Account created. Check your email to confirm the account, then login.');}currentUser=r.data.user;await ensureCandidate();await openPortal()};
$('forgotBtn').onclick=async()=>{if(!db)return msg('Supabase configuration is missing.');const email=prompt('Enter your registered email address');if(!email)return;const r=await db.auth.resetPasswordForEmail(email.trim(),{redirectTo:location.href});msg(r.error?r.error.message:'Password reset email sent.',!r.error)};
$('logout').onclick=async()=>{await db?.auth.signOut();location.reload()};
async function openPortal(){if(!currentCandidate)await ensureCandidate();$('authCard').hidden=true;$('portal').hidden=false;$('welcome').textContent='Welcome, '+(currentCandidate?.full_name||'Candidate');$('regLine').textContent='Registration No: '+(currentCandidate?.registration_no||'—');fillProfile();await Promise.all([loadApplications(),loadResults(),loadDocuments(),loadMessages()])}
function fillProfile(){const c=currentCandidate||{};[['pReg',c.registration_no],['pRoll',c.roll_no],['pName',c.full_name],['pEmail',c.email],['pPhone',c.phone],['pDob',c.dob],['pFather',c.father_name],['pMother',c.mother_name],['pCategory',c.category],['pAddress',c.address],['pCity',c.city],['pState',c.state],['pPincode',c.pincode]].forEach(([id,v])=>$(id).value=v||'');$('profileStatus').textContent=c.status||''}
$('profileForm').onsubmit=async e=>{e.preventDefault();const p={roll_no:$('pRoll').value.trim()||null,full_name:$('pName').value.trim(),phone:$('pPhone').value.trim()||null,dob:$('pDob').value||null,father_name:$('pFather').value.trim()||null,mother_name:$('pMother').value.trim()||null,category:$('pCategory').value||null,address:$('pAddress').value.trim()||null,city:$('pCity').value.trim()||null,state:$('pState').value.trim()||null,pincode:$('pPincode').value.trim()||null,updated_at:new Date().toISOString()};const r=await db.from('ssc_candidates').update(p).eq('user_id',currentUser.id);if(r.error)return toast(r.error.message);currentCandidate={...currentCandidate,...p};$('welcome').textContent='Welcome, '+currentCandidate.full_name;toast('Profile saved')};
document.querySelectorAll('.sidebtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sidebtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.hidden=true);$(b.dataset.section).hidden=false});
$('newApplication').onclick=()=>{$('applicationForm').hidden=false;$('aId').value='';$('aExam').value='';$('aPost').value='';$('aNo').value='';$('aQualification').value='';$('aYear').value='';$('aBoard').value='';$('aPercentage').value='';$('aCentre').value='';$('aAdditional').value='';};
$('cancelApplication').onclick=()=>{$('applicationForm').hidden=true};
function applicationData(n){const f=n.form_data||{};return {qualification:f.qualification||'',year:f.year||'',board:f.board||'',percentage:f.percentage||'',centre:f.centre||'',additional:f.additional||''}}
async function loadApplications(){const r=await db.from('ssc_applications').select('*').eq('candidate_id',currentUser.id).order('created_at',{ascending:false});if(r.error)return $('applicationList').innerHTML='<div class="item">'+esc(r.error.message)+'</div>';const a=r.data||[];$('applicationList').innerHTML=a.map(n=>{const f=applicationData(n);return `<article class="item"><div class="itemhead"><div><h3>${esc(n.exam_name)}</h3><div class="meta">Application: ${esc(n.application_no||'—')} · Post: ${esc(n.post_name||'—')}</div></div><span class="pill">${esc(n.status)}</span></div><div class="meta">Qualification: ${esc(f.qualification||'—')} · Year: ${esc(f.year||'—')} · Centre: ${esc(f.centre||'—')}</div><button class="outline editapp" data-id="${esc(n.id)}" style="margin-top:9px">Edit</button></article>`}).join('')||'<div class="item">No applications yet. Click “New Application” to start.</div>';document.querySelectorAll('.editapp').forEach(b=>b.onclick=()=>editApplication(a.find(x=>x.id===b.dataset.id)))}
function editApplication(n){const f=applicationData(n);$('aId').value=n.id;$('aExam').value=n.exam_name||'';$('aPost').value=n.post_name||'';$('aNo').value=n.application_no||'';$('aQualification').value=f.qualification;$('aYear').value=f.year;$('aBoard').value=f.board;$('aPercentage').value=f.percentage;$('aCentre').value=f.centre;$('aAdditional').value=f.additional;$('applicationForm').hidden=false}
$('applicationForm').onsubmit=async e=>{e.preventDefault();const form_data={qualification:$('aQualification').value.trim(),year:$('aYear').value.trim(),board:$('aBoard').value.trim(),percentage:$('aPercentage').value.trim(),centre:$('aCentre').value.trim(),additional:$('aAdditional').value.trim()};const id=$('aId').value;const payload={application_no:$('aNo').value.trim()||null,exam_name:$('aExam').value.trim(),post_name:$('aPost').value.trim()||null,status:'draft',form_data,updated_at:new Date().toISOString()};let r=id?await db.from('ssc_applications').update(payload).eq('id',id).eq('candidate_id',currentUser.id):await db.from('ssc_applications').insert({...payload,candidate_id:currentUser.id});if(r.error)return toast(r.error.message);$('applicationForm').hidden=true;toast('Application saved');loadApplications()};
async function loadResults(){const r=await db.from('ssc_results').select('*').eq('candidate_id',currentUser.id).eq('published',true).order('result_date',{ascending:false});if(r.error)return $('resultList').innerHTML='<div class="item">'+esc(r.error.message)+'</div>';const a=r.data||[];$('resultList').innerHTML=a.map(n=>`<article class="item"><div class="itemhead"><div><h3>${esc(n.exam_name)}</h3><div class="meta">${esc(n.result_date||'')}</div></div><span class="pill">${esc(n.selection_status||'Published')}</span></div><div class="meta">Post: ${esc(n.post_name||'—')} · Marks: ${esc(n.marks??'—')}/${esc(n.max_marks??'—')} · Rank: ${esc(n.rank||'—')} · Percentile: ${esc(n.percentile??'—')}</div><p>${esc(n.remarks||'')}</p></article>`).join('')||'<div class="item">No published result is available.</div>'}
async function loadDocuments(){const r=await db.from('ssc_candidate_documents').select('*').eq('candidate_id',currentUser.id).order('created_at',{ascending:false});if(r.error)return $('documentList').innerHTML='<div class="item">'+esc(r.error.message)+'</div>';const a=r.data||[];$('documentList').innerHTML=a.map(n=>`<article class="item"><div class="itemhead"><div><h3>${esc(n.title||n.document_type)}</h3><div class="meta">${esc(n.document_type)} · ${n.verified?'Verified':'Pending verification'}</div></div><span class="pill">${n.verified?'Verified':'Pending'}</span></div><a href="#" data-doc="${esc(n.file_path)}">Open document</a></article>`).join('')||'<div class="item">No documents uploaded.</div>';document.querySelectorAll('[data-doc]').forEach(a=>a.onclick=async e=>{e.preventDefault();const x=await db.storage.from('ssc-candidate-files').createSignedUrl(a.dataset.doc,300);if(x.error)return toast(x.error.message);window.open(x.data.signedUrl,'_blank','noopener')})}
$('docForm').onsubmit=async e=>{e.preventDefault();const file=$('docFile').files[0];if(!file)return;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${currentUser.id}/${Date.now()}-${safe}`;$('docMsg').textContent='Uploading…';const up=await db.storage.from('ssc-candidate-files').upload(path,await file.arrayBuffer(),{contentType:file.type||'application/octet-stream',upsert:false});if(up.error)return $('docMsg').textContent=up.error.message;const ins=await db.from('ssc_candidate_documents').insert({candidate_id:currentUser.id,document_type:$('docType').value,title:$('docTitle').value.trim()||file.name,file_path:path,verified:false});if(ins.error){await db.storage.from('ssc-candidate-files').remove([path]);return $('docMsg').textContent=ins.error.message}$('docMsg').textContent='Upload successful.';$('docFile').value='';$('docTitle').value='';loadDocuments()};
async function loadMessages(){const r=await db.from('ssc_candidate_messages').select('*').eq('candidate_id',currentUser.id).eq('published',true).order('created_at',{ascending:false});if(r.error)return $('messageList').innerHTML='<div class="item">'+esc(r.error.message)+'</div>';const a=r.data||[];$('messageList').innerHTML=a.map(n=>`<article class="item"><h3>${esc(n.title)}</h3><div class="meta">${esc(new Date(n.created_at).toLocaleString())}</div><p>${esc(n.body||'')}</p>${n.attachment_path?`<a href="#" data-msgfile="${esc(n.attachment_path)}">Open attachment</a>`:''}</article>`).join('')||'<div class="item">No messages.</div>'}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-msgfile]');if(!a)return;e.preventDefault();const x=await db.storage.from('ssc-candidate-files').createSignedUrl(a.dataset.msgfile,300);if(x.error)return toast(x.error.message);window.open(x.data.signedUrl,'_blank','noopener')});
window.addEventListener('DOMContentLoaded',async()=>{if(!db)return msg('Supabase configuration is missing.');const s=await session();if(s?.user){currentUser=s.user;await ensureCandidate();await openPortal()}});
