(() => {
'use strict';
const cfg=window.SSC_CONFIG||{};
const db=(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase)?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}}):null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const toast=t=>{const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)};
const refNo=()=>`PRTI-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
async function session(){if(!db)return null;const r=await db.auth.getSession();return r.data?.session||null;}
function rtiModal(){if(typeof modal!=='function')return;modal(`<div class="modal small"><div class="modalhead"><h3>Private RTI</h3><button class="close">×</button></div><div class="modalbody"><p class="muted">Submit your RTI question/application and receive the reply in your candidate account Messages.</p><div class="servicecard"><button class="serviceitem" id="privateRtiNew">New Private RTI <b>→</b></button><button class="serviceitem" id="privateRtiStatus">My RTI Status / Replies <b>→</b></button></div></div></div>`);$('privateRtiNew')?.addEventListener('click',newRti);$('privateRtiStatus')?.addEventListener('click',myRti)}
async function requireLogin(){const s=await session();if(!s){modal(`<div class="modal small"><div class="modalhead"><h3>Private RTI</h3><button class="close">×</button></div><div class="modalbody"><p>Please login to your Candidate account before submitting or viewing a Private RTI.</p><div class="center"><button class="pill" id="rtiLogin">Candidate Login</button></div></div></div>`);$('rtiLogin')?.addEventListener('click',()=>location.href='candidate.html?mode=login');return null}return s}
async function newRti(){const s=await requireLogin();if(!s)return;modal(`<div class="modal"><div class="modalhead"><h3>New Private RTI</h3><button class="close">×</button></div><div class="modalbody"><form id="privateRtiForm" class="formgrid"><label>Subject<input id="rtiSubject" required maxlength="200" placeholder="Enter RTI subject"></label><label class="wide">RTI Application / Question<textarea id="rtiText" required rows="8" maxlength="10000" placeholder="Write your question or application"></textarea></label><div class="wide actions"><button class="pill" type="submit">Submit Private RTI</button></div></form></div></div>`);$('privateRtiForm')?.addEventListener('submit',async e=>{e.preventDefault();const subject=$('rtiSubject')?.value.trim()||'',text=$('rtiText')?.value.trim()||'';if(!subject||!text)return toast('Enter subject and RTI application.');const c=await db.from('ssc_candidates').select('user_id').eq('user_id',s.user.id).maybeSingle();if(c.error)return toast(c.error.message);if(!c.data)return toast('Candidate profile not found. Please login again.');const reference_no=refNo();const r=await db.from('ssc_private_rti').insert({candidate_id:s.user.id,reference_no,subject,application_text:text,status:'Submitted'}).select().single();if(r.error)return toast(r.error.message);modal(`<div class="modal small"><div class="modalhead"><h3>Private RTI Submitted</h3><button class="close">×</button></div><div class="modalbody"><p>Your application has been submitted.</p><div class="card item"><b>Reference No.: ${esc(reference_no)}</b><p>Status: Submitted</p></div><p class="muted">Admin reply will appear in your Candidate Portal → Messages.</p></div></div>`)})}
async function myRti(){const s=await requireLogin();if(!s)return;const r=await db.from('ssc_private_rti').select('*').eq('candidate_id',s.user.id).order('created_at',{ascending:false});if(r.error)return toast(r.error.message);modal(`<div class="modal"><div class="modalhead"><h3>My Private RTI</h3><button class="close">×</button></div><div class="modalbody">${(r.data||[]).length?(r.data||[]).map(x=>`<article class="item"><div class="itemhead"><div><h3>${esc(x.subject)}</h3><div class="meta">Reference: ${esc(x.reference_no)} · ${esc(x.status)}</div></div><span class="pill">${esc(x.status)}</span></div><p>${esc(x.application_text)}</p>${x.admin_reply?`<div class="card item"><b>Admin Reply</b><p>${esc(x.admin_reply)}</p><small>${esc(x.replied_at||'')}</small></div>`:'<p class="muted">Reply not yet issued.</p>'}</article>`).join(''):'<p class="muted">No Private RTI applications found.</p>'}</div></div>`)}
async function candidateMode(){const side=document.querySelector('.dashboard .side');if(side&&!side.querySelector('[data-section="private-rti"]')){const b=document.createElement('button');b.type='button';b.className='sidebtn';b.dataset.section='private-rti';b.textContent='Private RTI';side.appendChild(b);b.addEventListener('click',showCandidateRti)}if($('private-rti-view'))return;const content=document.querySelector('.dashboard .content');if(!content)return;const v=document.createElement('div');v.id='private-rti-view';v.className='view';v.hidden=true;v.innerHTML=`<div class="sectionTitle"><div><h2>Private RTI</h2><p class="muted">Submit an RTI question and receive Admin replies in Messages.</p></div><button id="candidateRtiNew" class="primary" type="button">+ New Private RTI</button></div><div id="candidateRtiList" class="stack"></div>`;content.appendChild(v);$('candidateRtiNew')?.addEventListener('click',candidateNewRti);loadCandidateRti()}
function showCandidateRti(){document.querySelectorAll('.dashboard .view').forEach(v=>v.hidden=true);document.querySelectorAll('.dashboard .sidebtn').forEach(b=>b.classList.toggle('active',b.dataset.section==='private-rti'));$('private-rti-view').hidden=false;loadCandidateRti()}
async function loadCandidateRti(){const el=$('candidateRtiList');if(!el||!db)return;const s=await session();if(!s){el.innerHTML='<div class="item">Please login again.</div>';return}const r=await db.from('ssc_private_rti').select('*').eq('candidate_id',s.user.id).order('created_at',{ascending:false});if(r.error){el.innerHTML=`<div class="item">${esc(r.error.message)}</div>`;return}el.innerHTML=(r.data||[]).map(x=>`<article class="item"><div class="itemhead"><div><h3>${esc(x.subject)}</h3><div class="meta">Reference No.: ${esc(x.reference_no)}</div></div><span class="pill">${esc(x.status)}</span></div><p>${esc(x.application_text)}</p>${x.admin_reply?`<div class="card item"><b>Admin Reply</b><p>${esc(x.admin_reply)}</p><small>${esc(x.replied_at||'')}</small></div>`:'<p class="muted">Admin reply is pending.</p>'}</article>`).join('')||'<div class="item">No Private RTI applications yet.</div>'}
async function candidateNewRti(){const s=await session();if(!s){location.href='candidate.html?mode=login';return}const subject=prompt('Private RTI Subject');if(!subject?.trim())return;const text=prompt('Write your RTI application / question');if(!text?.trim())return;const r=await db.from('ssc_private_rti').insert({candidate_id:s.user.id,reference_no:refNo(),subject:subject.trim(),application_text:text.trim(),status:'Submitted'});if(r.error)return toast(r.error.message);toast('Private RTI submitted successfully.');loadCandidateRti()}
async function candidateMessages(){const el=$('messageList');if(!el||!db)return;const s=await session();if(!s)return;const r=await db.from('ssc_private_rti_messages').select('*').eq('candidate_id',s.user.id).order('created_at',{ascending:false});if(r.error)return;const rows=r.data||[];if(!rows.length)return;const html=rows.map(x=>`<article class="item"><div class="itemhead"><div><h3>${esc(x.title||'Private RTI Reply')}</h3><div class="meta">${esc(x.created_at||'')}</div></div><span class="pill">RTI</span></div><p>${esc(x.body)}</p></article>`).join('');el.insertAdjacentHTML('afterbegin',html)}
async function adminMode(){const manager=$('manager');if(!manager||$('privateRtiAdmin'))return;const box=document.createElement('section');box.id='privateRtiAdmin';box.className='admin-section';box.innerHTML=`<hr><h2>Private RTI</h2><p>RTI applications from candidates.</p><div id="privateRtiAdminList"></div>`;manager.appendChild(box);loadAdminRti()}
async function loadAdminRti(){const el=$('privateRtiAdminList');if(!el||!db)return;const r=await db.from('ssc_private_rti').select('*').order('created_at',{ascending:false});if(r.error){el.innerHTML=`<div class="card"><p>${esc(r.error.message)}</p></div>`;return}el.innerHTML=(r.data||[]).map(x=>`<article class="card" style="padding:16px;margin:12px 0"><b>${esc(x.subject)}</b><div>Reference: ${esc(x.reference_no)} · Status: ${esc(x.status)}</div><p>${esc(x.application_text)}</p>${x.admin_reply?`<div><b>Current Reply:</b><p>${esc(x.admin_reply)}</p></div>`:''}<textarea id="reply-${esc(x.id)}" rows="4" style="width:100%" placeholder="Write reply to candidate">${esc(x.admin_reply||'')}</textarea><button type="button" class="primary" data-rti-reply="${esc(x.id)}">${x.admin_reply?'Update Reply':'Send Reply'}</button></article>`).join('')||'<div class="card"><p>No Private RTI applications yet.</p></div>';document.querySelectorAll('[data-rti-reply]').forEach(b=>b.onclick=()=>replyRti(b.dataset.rtiReply))}
async function replyRti(id){const text=$(`reply-${id}`)?.value.trim()||'';if(!text)return toast('Write a reply first.');const r=await db.from('ssc_private_rti').update({admin_reply:text,status:'Replied',replied_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).select().single();if(r.error)return toast(r.error.message);const x=r.data;const m=await db.from('ssc_private_rti_messages').insert({rti_id:id,candidate_id:x.candidate_id,title:'Private RTI Reply',body:text});if(m.error)return toast('RTI updated, but candidate message could not be created: '+m.error.message);toast('Reply sent to candidate Messages.');loadAdminRti()}
function indexMode(){document.addEventListener('click',e=>{const b=e.target.closest('[data-route="rti-online"]');if(b){e.preventDefault();e.stopImmediatePropagation();rtiModal()}},true)}
function boot(){const p=location.pathname.split('/').pop().toLowerCase();if(p==='index.html'||p==='')indexMode();if(p==='candidate.html'){const w=setInterval(()=>{if(document.querySelector('.dashboard .side')){clearInterval(w);candidateMode();candidateMessages()}},300)}if(p==='admin.html'){const w=setInterval(()=>{if($('manager')&&!$('manager').hidden){clearInterval(w);adminMode()}},300)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
